apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default "grafana-pdc-agent" }}
type: Opaque
data:
  "token": {{ .Values.secret.values.token | required "secret-value missing: token" | b64enc | quote }}
  "hosted-grafana-id": {{ .Values.secret.values.hostedgrafanaid | required "secret-value missing: hostedgrafanaid" | b64enc | quote }}
  "cluster": {{ .Values.secret.values.cluster | required "secret-value missing: cluster" | b64enc | quote }}
